### ISSUE TITLE
webserver::running is true before starting MHD_Deamon ?

### ISSUE THREAD

**Issue by GMercat** [etr/libhttpserver#103]
Hello,

When we start the webserver, we don't know when exactly it's ready to work. We use `webserver::is_running()` but it return true even if the MHD_Deamon isn't started.

Which state is according to `webserver::running` ? During tests, when we start webserver, we wait for the "webserver::running" change to true but the server isn't up. We have a nasty workaround with a sleep, but it doesn't work sometimes.

In "src/webserver.cpp", why the line 362 is before MHD_start_deamon ? [https://github.com/etr/libhttpserver/blob/master/src/webserver.cpp#L362](url)

How can we know when the webserver it's ready to work ?

Thanks
G.

**Comment by etr** [comment]
Hi,
that is definitely a bug. It should be fixed on head now - can you let me know if it works for you?

Thanks!
