### ISSUE TITLE
Benchmark example gives garbled output

### ISSUE THREAD

**Issue by rajathvsm** [etr/libhttpserver#104]
When I compile benchmark, this is what I get:

```
$ curl 127.0.0.1:8080/
������le>libmicrohttpd demo</title></head><body>libhttpserver demo</body></html>

```

When I modify hello_world.cpp to return data instead of the supplied string, if I use a sufficiently long data, then again I get a garbled string back. The encoding is set to UTF-8.

```
$ curl 127.0.0.1:8080/hello?data=1234567890
1234567890
$ curl 127.0.0.1:8080/hello?data=1234567890
$ curl 127.0.0.1:8080/hello?data=123456789012345
123456789012345
$ curl 127.0.0.1:8080/hello?data=1234567890123456
Content-Type456
$ curl 127.0.0.1:8080/hello?data=123456789012345678901234567890
���U��U90
```

I see that whenever the content is or exceeds 16 bytes, it gets affected. Does anybody else have this issue?

**Comment by etr** [comment]
It doesn't seem to be happening with the latest version. Closing this as it is out of date.
