### ISSUE TITLE
Unable to bind with given ipaddress

### ISSUE THREAD

**Issue by atpb** [etr/libhttpserver#106]
Hi all,
I'm trying to the access to the httpserver at a given ipaddress and port number.. I'm using the constructor as:
struct sockaddr_in serv_addr;
/* Initialize socket structure */
bzero((char *) &serv_addr, sizeof(serv_addr));

serv_addr.sin_family = AF_INET;
serv_addr.sin_addr.s_addr =inet_addr("10.10.10.100");
serv_addr.sin_port = htons(5001);
create_webserver cw = create_webserver(5001).max_threads(5).bind_address((struct sockaddr *) &serv_addr);

But the application is bind to default ip address 0.0.0.0:5001, How do I make server bind to given ip address 10.10.10.100 ?

**Comment by etr** [comment]
Sorry for the delay of this answer. I tried to fix this bug for a while now.

Through trial I found that libmicrohttpd seems not to be using the MHD_OPTION_SOCK_ADDR when used from inside MHD_OPTION_ARRAY. I am forcing the option separately and this seems to be working for me now.

Thanks for your patience. Let me know if you have ant other issue.

**Comment by atpb** [comment]
Is this change available in the new release ? or git pull ?

**Comment by etr** [comment]
Currently on master. I am going to create a new release in the next few
hours.
