### ISSUE TITLE
Current stable version?

### ISSUE THREAD

**Issue by ilovezfs** [etr/libhttpserver#114]
Based on https://github.com/etr/libhttpserver/releases I cannot tell if 0.13.0, 0.9.0, or something else besides either of them, is the current stable version.

Which version should be in Homebrew's `stable` spec? Thanks!

**Comment by etr** [comment]
Hi,
sorry for the confusion in the release page - 0.13.0 is the latest stable release.

Best,
Sebastiano

**Comment by ilovezfs** [comment]
@etr thanks for clearing that up. Do you mind deleting the explicit 0.9.0 release so that https://github.com/etr/libhttpserver/releases/latest doesn't point to incorrect information? The delete button is on the page https://github.com/etr/libhttpserver/releases/tag/v0.9.0.

**Comment by etr** [comment]
Sure thing. Thanks.

**Comment by ilovezfs** [comment]
perfect. thank you!
