### ISSUE TITLE
How to set http headers

### ISSUE THREAD

**Issue by douglascordeiro** [etr/libhttpserver#117]
Hi I do not get how to set headers with http_response_builder. I need to set some headers

**Comment by dre** [comment]
Hey Douglas, I set them like this ...

...
http_response_builder hrb("some string", 200);
...
hrb.with_header("hdr_key",  "hdr_val");
...

and I know that works as I am running this in a prod env. Hope that helps.

**Comment by etr** [comment]
The answer from dre is the most correct one.

Thanks for helping here.
