### ISSUE TITLE
Compilation error when using g++ v6.3.0  c++11

### ISSUE THREAD

**Issue by davidoz99** [etr/libhttpserver#118]
Hi All,

This is just a heads up for anyone compiling the http server using a new-ish gcc compiler.  My v6.3.0 g++ compiler generates an error in method:

`bool webserver::register_resource(const std::string& resource, http_resource* hrm, bool family)`

It is unable to copy the `details::http_endpoint` object when it is inserted into the `registered_resources` map.  It looks like the compiler is using different STL classes to do the copying and destroying than the ones before.  Unlike `std::pair`, these other classes are not friends of `details::http_endpoint`.

To temporarily workaround the issue I simply made the copy and destructor methods of `details::http_endpoint` public.

```
public:
        http_endpoint(const http_endpoint& h);
        ~http_endpoint();
private:
    ....
```

When the newer compilers are supported, a permanent solution will need to identify which new STLs are interacting with `details::http_endpoint` so they can also be made friends.  It might be std::tuple and/or std::forward(), but I'm not completely sure.

Thanks.

**Comment by etr** [comment]
Thanks for letting me know.

The latest version on head (and the latest release) should tackle the problem implicitly.

In this, http_endpoint is a class nested within "webserver" (which was the only user of it). This allows for a cleaner indication of it being nested and doesn't require the use of friends.

Let me know if this works for your case.

I am also setting-up travis runs for g++6 to make sure nothing else breaks in newer versions of GCC.

**Comment by etr** [comment]
@davidoz99 please re-open if this is not fixed for you. The travis builds are passing on g++6 with tests  passing.
