### ISSUE TITLE
How to handle post requests

### ISSUE THREAD

**Issue by Tarik-M** [etr/libhttpserver#121]
Hi,

I have looked at the library for a while and was wondering how POST requests are handled. As far as I can see, the only way to get the contents of a request is via get_content() which just returns a string of the payload.

Any suggestions on how to search/extract each form by itself? Example would be having one form be some text and another form being a file.

thanks

**Comment by etr** [comment]
Hi,

you really have two ways to handle POST requests.

1) If your body is url-encoded, you can enable a post-processor and use
getArg to get the arguments
2) If your body is not url-encoded you'll have to handle the parsing of the
content yourself through get_content()

Does 1) cover your use case?

Regards,
Sebastiano

**Comment by etr** [comment]
The post-processor is there unless disabled through compile configuration.

What do you mean by "without it being in a string?". Are you talking about you passing a "type" to the method and having the method building an object for you?

**Comment by Tarik-M** [comment]
Hi,

I was thinking about the way that data is read into a variable. Currently the data is stored in a string variable, but since I pass it to memory afterwards, it isn't a big deal. It was just a thought if reading data from req.get_arg into a string was the way to go. I think i'll close the issue since I solved the problem. Thanks for the help :)
