### ISSUE TITLE
compile error after ubuntu update

### ISSUE THREAD

**Issue by Rajkumar181** [etr/libhttpserver#123]
Hi Team,
     Previously i am able to compile my project. but after updating my Ubuntu desktop , i am getting this error.

/usr/bin/ld: warning: libmicrohttpd.so.10, needed by //usr/local/lib/libhttpserver.so, not found (try using -rpath or -rpath-link)
//usr/local/lib/libhttpserver.so: undefined reference to `MHD_queue_basic_auth_fail_response'
//usr/local/lib/libhttpserver.so: undefined reference to `MHD_digest_auth_check'
//usr/local/lib/libhttpserver.so: undefined reference to `MHD_resume_connection'
//usr/local/lib/libhttpserver.so: undefined reference to `MHD_post_process'
//usr/local/lib/libhttpserver.so: undefined reference to `MHD_lookup_connection_value'
//usr/local/lib/libhttpserver.so: undefined reference to `MHD_get_connection_info'
//usr/local/lib/libhttpserver.so: undefined reference to `MHD_create_response_from_fd'
//usr/local/lib/libhttpserver.so: undefined reference to `MHD_suspend_connection'
//usr/local/lib/libhttpserver.so: undefined reference to `MHD_stop_daemon'
//usr/local/lib/libhttpserver.so: undefined reference to `MHD_create_post_processor'
//usr/local/lib/libhttpserver.so: undefined reference to `MHD_get_connection_values'
//usr/local/lib/libhttpserver.so: undefined reference to `MHD_queue_auth_fail_response'
//usr/local/lib/libhttpserver.so: undefined reference to `MHD_queue_response'
//usr/local/lib/libhttpserver.so: undefined reference to `MHD_create_response_from_callback'
//usr/local/lib/libhttpserver.so: undefined reference to `MHD_destroy_post_processor'
//usr/local/lib/libhttpserver.so: undefined reference to `MHD_add_response_header'
//usr/local/lib/libhttpserver.so: undefined reference to `MHD_start_daemon'
//usr/local/lib/libhttpserver.so: undefined reference to `MHD_create_response_from_buffer'
//usr/local/lib/libhttpserver.so: undefined reference to `MHD_digest_auth_get_username'
//usr/local/lib/libhttpserver.so: undefined reference to `MHD_basic_auth_get_username_password'
//usr/local/lib/libhttpserver.so: undefined reference to `MHD_add_response_footer'
//usr/local/lib/libhttpserver.so: undefined reference to `MHD_destroy_response'
collect2: error: ld returned 1 exit status

**Comment by Rajkumar181** [comment]
i tried to rebuild and make install but again i getting different error.



Making all in src
make[2]: Entering directory '/home/iram14/Downloads/httpserver/libhttpserver/build/src'
/bin/bash ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../../src -I..  -I../ -I../../src/httpserver/  -O3 -fPIC -Wall  -DUSE_FASTOPEN -DHTTPSERVER_COMPILATION -D_REENTRANT   -MT libhttpserver_la-webserver.lo -MD -MP -MF .deps/libhttpserver_la-webserver.Tpo -c -o libhttpserver_la-webserver.lo `test -f 'webserver.cpp' || echo '../../src/'`webserver.cpp
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../../src -I.. -I../ -I../../src/httpserver/ -O3 -fPIC -Wall -DUSE_FASTOPEN -DHTTPSERVER_COMPILATION -D_REENTRANT -MT libhttpserver_la-webserver.lo -MD -MP -MF .deps/libhttpserver_la-webserver.Tpo -c ../../src/webserver.cpp  -fPIC -DPIC -o .libs/libhttpserver_la-webserver.o
../../src/webserver.cpp: In member function ‘bool httpserver::webserver::register_resource(const string&, httpserver::http_resource*, bool)’:
../../src/webserver.cpp:230:73: error: no matching function for call to ‘std::pair<const httpserver::details::http_endpoint, httpserver::http_resource*>::pair(httpserver::details::http_endpoint&, httpserver::http_resource*&)’
         map<details::http_endpoint, http_resource*>::value_type(idx, hrm)
                                                                         ^
In file included from /usr/include/c++/7/bits/stl_algobase.h:64:0,
                 from /usr/include/c++/7/bits/char_traits.h:39,
                 from /usr/include/c++/7/ios:40,
                 from /usr/include/c++/7/ostream:38,
                 from /usr/include/c++/7/iostream:39,
                 from ../../src/webserver.cpp:23:
/usr/include/c++/7/bits/stl_pair.h:431:9: note: candidate: template<class ... _Args1, long unsigned int ..._Indexes1, class ... _Args2, long unsigned int ..._Indexes2> std::pair<_T1, _T2>::pair(std::tuple<_Args1 ...>&, std::tuple<_Args2 ...>&, std::_Index_tuple<_Indexes1 ...>, std::_Index_tuple<_Indexes2 ...>)
         pair(tuple<_Args1...>&, tuple<_Args2...>&,
         ^~~~
/usr/include/c++/7/bits/stl_pair.h:431:9: note:   template argument deduction/substitution failed:
../../src/webserver.cpp:230:73: note:   ‘httpserver::details::http_endpoint’ is not derived from ‘std::tuple<_Tps ...>’
         map<details::http_endpoint, http_resource*>::value_type(idx, hrm)
                                                                         ^
In file included from /usr/include/c++/7/bits/stl_algobase.h:64:0,
                 from /usr/include/c++/7/bits/char_traits.h:39,
                 from /usr/include/c++/7/ios:40,
                 from /usr/include/c++/7/ostream:38,
                 from /usr/include/c++/7/iostream:39,
                 from ../../src/webserver.cpp:23:
/usr/include/c++/7/bits/stl_pair.h:364:9: note: candidate: template<class ... _Args1, class ... _Args2> std::pair<_T1, _T2>::pair(std::piecewise_construct_t, std::tuple<_Args1 ...>, std::tuple<_Args2 ...>)
         pair(piecewise_construct_t, tuple<_Args1...>, tuple<_Args2...>);
         ^~~~
/usr/include/c++/7/bits/stl_pair.h:364:9: note:   template argument deduction/substitution failed:
../../src/webserver.cpp:230:73: note:   mismatched types ‘std::tuple<_Tps ...>’ and ‘httpserver::http_resource*’
         map<details::http_endpoint, http_resource*>::value_type(idx, hrm)
                                                                         ^
In file included from /usr/include/c++/7/bits/stl_algobase.h:64:0,
                 from /usr/include/c++/7/bits/char_traits.h:39,
                 from /usr/include/c++/7/ios:40,
                 from /usr/include/c++/7/ostream:38,
                 from /usr/include/c++/7/iostream:39,
                 from ../../src/webserver.cpp:23:
/usr/include/c++/7/bits/stl_pair.h:359:21: note: candidate: template<class _U1, class _U2, typename std::enable_if<(std::_PCC<((! std::is_same<const httpserver::details::http_endpoint, _U1>::value) || (! std::is_same<httpserver::http_resource*, _U2>::value)), const httpserver::details::http_endpoint, httpserver::http_resource*>::_MoveConstructiblePair<_U1, _U2>() && (! std::_PCC<((! std::is_same<const httpserver::details::http_endpoint, _U1>::value) || (! std::is_same<httpserver::http_resource*, _U2>::value)), const httpserver::details::http_endpoint, httpserver::http_resource*>::_ImplicitlyMoveConvertiblePair<_U1, _U2>())), bool>::type <anonymous> > constexpr std::pair<_T1, _T2>::pair(std::pair<_U1, _U2>&&)
  explicit constexpr pair(pair<_U1, _U2>&& __p)
                     ^~~~
/usr/include/c++/7/bits/stl_pair.h:359:21: note:   template argument deduction/substitution failed:
../../src/webserver.cpp:230:73: note:   ‘httpserver::details::http_endpoint’ is not derived from ‘std::pair<_T1, _T2>’
         map<details::http_endpoint, http_resource*>::value_type(idx, hrm)
                                                                         ^
In file included from /usr/include/c++/7/bits/stl_algobase.h:64:0,
                 from /usr/include/c++/7/bits/char_traits.h:39,
                 from /usr/include/c++/7/ios:40,
                 from /usr/include/c++/7/ostream:38,
                 from /usr/include/c++/7/iostream:39,
                 from ../../src/webserver.cpp:23:
/usr/include/c++/7/bits/stl_pair.h:349:12: note: candidate: template<class _U1, class _U2, typename std::enable_if<(std::_PCC<((! std::is_same<const httpserver::details::http_endpoint, _U1>::value) || (! std::is_same<httpserver::http_resource*, _U2>::value)), const httpserver::details::http_endpoint, httpserver::http_resource*>::_MoveConstructiblePair<_U1, _U2>() && std::_PCC<((! std::is_same<const httpserver::details::http_endpoint, _U1>::value) || (! std::is_same<httpserver::http_resource*, _U2>::value)), const httpserver::details::http_endpoint, httpserver::http_resource*>::_ImplicitlyMoveConvertiblePair<_U1, _U2>()), bool>::type <anonymous> > constexpr std::pair<_T1, _T2>::pair(std::pair<_U1, _U2>&&)
  constexpr pair(pair<_U1, _U2>&& __p)
            ^~~~
/usr/include/c++/7/bits/stl_pair.h:349:12: note:   template argument deduction/substitution failed:
../../src/webserver.cpp:230:73: note:   ‘httpserver::details::http_endpoint’ is not derived from ‘std::pair<_T1, _T2>’
         map<details::http_endpoint, http_resource*>::value_type(idx, hrm)
                                                                         ^
In file included from /usr/include/c++/7/bits/stl_algobase.h:64:0,
                 from /usr/include/c++/7/bits/char_traits.h:39,
                 from /usr/include/c++/7/ios:40,
                 from /usr/include/c++/7/ostream:38,
                 from /usr/include/c++/7/iostream:39,
                 from ../../src/webserver.cpp:23:
/usr/include/c++/7/bits/stl_pair.h:339:21: note: candidate: template<class _U1, class _U2, typename std::enable_if<(_MoveConstructiblePair<_U1, _U2>() && (! _ImplicitlyMoveConvertiblePair<_U1, _U2>())), bool>::type <anonymous> > constexpr std::pair<_T1, _T2>::pair(_U1&&, _U2&&)
  explicit constexpr pair(_U1&& __x, _U2&& __y)
                     ^~~~
/usr/include/c++/7/bits/stl_pair.h:339:21: note:   template argument deduction/substitution failed:
/usr/include/c++/7/bits/stl_pair.h:338:38: error: no type named ‘type’ in ‘struct std::enable_if<false, bool>’
                          bool>::type=false>
                                      ^~~~~
/usr/include/c++/7/bits/stl_pair.h:338:38: note: invalid template non-type parameter
/usr/include/c++/7/bits/stl_pair.h:330:12: note: candidate: template<class _U1, class _U2, typename std::enable_if<(_MoveConstructiblePair<_U1, _U2>() && _ImplicitlyMoveConvertiblePair<_U1, _U2>()), bool>::type <anonymous> > constexpr std::pair<_T1, _T2>::pair(_U1&&, _U2&&)
  constexpr pair(_U1&& __x, _U2&& __y)
            ^~~~
/usr/include/c++/7/bits/stl_pair.h:330:12: note:   template argument deduction/substitution failed:
/usr/include/c++/7/bits/stl_pair.h:329:38: error: no type named ‘type’ in ‘struct std::enable_if<false, bool>’
                          bool>::type=true>
                                      ^~~~
/usr/include/c++/7/bits/stl_pair.h:329:38: note: invalid template non-type parameter
/usr/include/c++/7/bits/stl_pair.h:321:17: note: candidate: template<class _U2, typename std::enable_if<_CopyMovePair<false, const httpserver::details::http_endpoint, _U2>(), bool>::type <anonymous> > std::pair<_T1, _T2>::pair(const _T1&, _U2&&)
        explicit pair(const _T1& __x, _U2&& __y)
                 ^~~~
/usr/include/c++/7/bits/stl_pair.h:321:17: note:   template argument deduction/substitution failed:
/usr/include/c++/7/bits/stl_pair.h:320:38: error: no type named ‘type’ in ‘struct std::enable_if<false, bool>’
                          bool>::type=false>
                                      ^~~~~
/usr/include/c++/7/bits/stl_pair.h:320:38: note: invalid template non-type parameter
/usr/include/c++/7/bits/stl_pair.h:314:18: note: candidate: template<class _U2, typename std::enable_if<_CopyMovePair<true, const httpserver::details::http_endpoint, _U2>(), bool>::type <anonymous> > constexpr std::pair<_T1, _T2>::pair(const _T1&, _U2&&)
        constexpr pair(const _T1& __x, _U2&& __y)
                  ^~~~
/usr/include/c++/7/bits/stl_pair.h:314:18: note:   template argument deduction/substitution failed:
/usr/include/c++/7/bits/stl_pair.h:313:38: error: no type named ‘type’ in ‘struct std::enable_if<false, bool>’
                          bool>::type=true>
                                      ^~~~
/usr/include/c++/7/bits/stl_pair.h:313:38: note: invalid template non-type parameter
/usr/include/c++/7/bits/stl_pair.h:307:27: note: candidate: template<class _U1, typename std::enable_if<_MoveCopyPair<false, _U1, httpserver::http_resource*>(), bool>::type <anonymous> > constexpr std::pair<_T1, _T2>::pair(_U1&&, const _T2&)
        explicit constexpr pair(_U1&& __x, const _T2& __y)
                           ^~~~
/usr/include/c++/7/bits/stl_pair.h:307:27: note:   template argument deduction/substitution failed:
/usr/include/c++/7/bits/stl_pair.h:306:38: error: no type named ‘type’ in ‘struct std::enable_if<false, bool>’
                          bool>::type=false>
                                      ^~~~~
/usr/include/c++/7/bits/stl_pair.h:306:38: note: invalid template non-type parameter
/usr/include/c++/7/bits/stl_pair.h:300:18: note: candidate: template<class _U1, typename std::enable_if<_MoveCopyPair<true, _U1, httpserver::http_resource*>(), bool>::type <anonymous> > constexpr std::pair<_T1, _T2>::pair(_U1&&, const _T2&)
        constexpr pair(_U1&& __x, const _T2& __y)
                  ^~~~
/usr/include/c++/7/bits/stl_pair.h:300:18: note:   template argument deduction/substitution failed:
/usr/include/c++/7/bits/stl_pair.h:299:38: error: no type named ‘type’ in ‘struct std::enable_if<false, bool>’
                          bool>::type=true>
                                      ^~~~
/usr/include/c++/7/bits/stl_pair.h:299:38: note: invalid template non-type parameter
/usr/include/c++/7/bits/stl_pair.h:293:17: note: candidate: std::pair<_T1, _T2>::pair(std::pair<_T1, _T2>&&) [with _T1 = const httpserver::details::http_endpoint; _T2 = httpserver::http_resource*]
       constexpr pair(pair&&) = default;
                 ^~~~
/usr/include/c++/7/bits/stl_pair.h:293:17: note:   candidate expects 1 argument, 2 provided
/usr/include/c++/7/bits/stl_pair.h:292:17: note: candidate: std::pair<_T1, _T2>::pair(const std::pair<_T1, _T2>&) [with _T1 = const httpserver::details::http_endpoint; _T2 = httpserver::http_resource*]
       constexpr pair(const pair&) = default;
                 ^~~~
/usr/include/c++/7/bits/stl_pair.h:292:17: note:   candidate expects 1 argument, 2 provided
/usr/include/c++/7/bits/stl_pair.h:289:21: note: candidate: template<class _U1, class _U2, typename std::enable_if<(std::_PCC<((! std::is_same<const httpserver::details::http_endpoint, _U1>::value) || (! std::is_same<httpserver::http_resource*, _U2>::value)), const httpserver::details::http_endpoint, httpserver::http_resource*>::_ConstructiblePair<_U1, _U2>() && (! std::_PCC<((! std::is_same<const httpserver::details::http_endpoint, _U1>::value) || (! std::is_same<httpserver::http_resource*, _U2>::value)), const httpserver::details::http_endpoint, httpserver::http_resource*>::_ImplicitlyConvertiblePair<_U1, _U2>())), bool>::type <anonymous> > constexpr std::pair<_T1, _T2>::pair(const std::pair<_U1, _U2>&)
  explicit constexpr pair(const pair<_U1, _U2>& __p)
                     ^~~~
/usr/include/c++/7/bits/stl_pair.h:289:21: note:   template argument deduction/substitution failed:
../../src/webserver.cpp:230:73: note:   ‘httpserver::details::http_endpoint’ is not derived from ‘const std::pair<_T1, _T2>’
         map<details::http_endpoint, http_resource*>::value_type(idx, hrm)
                                                                         ^
In file included from /usr/include/c++/7/bits/stl_algobase.h:64:0,
                 from /usr/include/c++/7/bits/char_traits.h:39,
                 from /usr/include/c++/7/ios:40,
                 from /usr/include/c++/7/ostream:38,
                 from /usr/include/c++/7/iostream:39,
                 from ../../src/webserver.cpp:23:
/usr/include/c++/7/bits/stl_pair.h:280:19: note: candidate: template<class _U1, class _U2, typename std::enable_if<(std::_PCC<((! std::is_same<const httpserver::details::http_endpoint, _U1>::value) || (! std::is_same<httpserver::http_resource*, _U2>::value)), const httpserver::details::http_endpoint, httpserver::http_resource*>::_ConstructiblePair<_U1, _U2>() && std::_PCC<((! std::is_same<const httpserver::details::http_endpoint, _U1>::value) || (! std::is_same<httpserver::http_resource*, _U2>::value)), const httpserver::details::http_endpoint, httpserver::http_resource*>::_ImplicitlyConvertiblePair<_U1, _U2>()), bool>::type <anonymous> > constexpr std::pair<_T1, _T2>::pair(const std::pair<_U1, _U2>&)
         constexpr pair(const pair<_U1, _U2>& __p)
                   ^~~~
/usr/include/c++/7/bits/stl_pair.h:280:19: note:   template argument deduction/substitution failed:
../../src/webserver.cpp:230:73: note:   ‘httpserver::details::http_endpoint’ is not derived from ‘const std::pair<_T1, _T2>’
         map<details::http_endpoint, http_resource*>::value_type(idx, hrm)
                                                                         ^
In file included from /usr/include/c++/7/bits/stl_algobase.h:64:0,
                 from /usr/include/c++/7/bits/char_traits.h:39,
                 from /usr/include/c++/7/ios:40,
                 from /usr/include/c++/7/ostream:38,
                 from /usr/include/c++/7/iostream:39,
                 from ../../src/webserver.cpp:23:
/usr/include/c++/7/bits/stl_pair.h:258:26: note: candidate: template<class _U1, class _U2, typename std::enable_if<(_ConstructiblePair<_U1, _U2>() && (! _ImplicitlyConvertiblePair<_U1, _U2>())), bool>::type <anonymous> > constexpr std::pair<_T1, _T2>::pair(const _T1&, const _T2&)
       explicit constexpr pair(const _T1& __a, const _T2& __b)
                          ^~~~
/usr/include/c++/7/bits/stl_pair.h:258:26: note:   template argument deduction/substitution failed:
/usr/include/c++/7/bits/stl_pair.h:257:38: error: no type named ‘type’ in ‘struct std::enable_if<false, bool>’
                          bool>::type=false>
                                      ^~~~~
/usr/include/c++/7/bits/stl_pair.h:257:38: note: invalid template non-type parameter
/usr/include/c++/7/bits/stl_pair.h:249:17: note: candidate: template<class _U1, class _U2, typename std::enable_if<(_ConstructiblePair<_U1, _U2>() && _ImplicitlyConvertiblePair<_U1, _U2>()), bool>::type <anonymous> > constexpr std::pair<_T1, _T2>::pair(const _T1&, const _T2&)
       constexpr pair(const _T1& __a, const _T2& __b)
                 ^~~~
/usr/include/c++/7/bits/stl_pair.h:249:17: note:   template argument deduction/substitution failed:
/usr/include/c++/7/bits/stl_pair.h:248:38: error: no type named ‘type’ in ‘struct std::enable_if<false, bool>’
                          bool>::type=true>
                                      ^~~~
/usr/include/c++/7/bits/stl_pair.h:248:38: note: invalid template non-type parameter
/usr/include/c++/7/bits/stl_pair.h:231:26: note: candidate: template<class _U1, class _U2, typename std::enable_if<std::__and_<std::is_default_constructible<_Tp>, std::is_default_constructible<_U2>, std::__not_<std::__and_<std::__is_implicitly_default_constructible<_U1>, std::__is_implicitly_default_constructible<_U2> > > >::value, bool>::type <anonymous> > constexpr std::pair<_T1, _T2>::pair()
       explicit constexpr pair()
                          ^~~~
/usr/include/c++/7/bits/stl_pair.h:231:26: note:   template argument deduction/substitution failed:
../../src/webserver.cpp:230:73: note:   candidate expects 0 arguments, 2 provided
         map<details::http_endpoint, http_resource*>::value_type(idx, hrm)
                                                                         ^
In file included from /usr/include/c++/7/bits/stl_algobase.h:64:0,
                 from /usr/include/c++/7/bits/char_traits.h:39,
                 from /usr/include/c++/7/ios:40,
                 from /usr/include/c++/7/ostream:38,
                 from /usr/include/c++/7/iostream:39,
                 from ../../src/webserver.cpp:23:
/usr/include/c++/7/bits/stl_pair.h:218:26: note: candidate: template<class _U1, class _U2, typename std::enable_if<std::__and_<std::__is_implicitly_default_constructible<_U1>, std::__is_implicitly_default_constructible<_U2> >::value, bool>::type <anonymous> > constexpr std::pair<_T1, _T2>::pair()
       _GLIBCXX_CONSTEXPR pair()
                          ^~~~
/usr/include/c++/7/bits/stl_pair.h:218:26: note:   template argument deduction/substitution failed:
../../src/webserver.cpp:230:73: note:   candidate expects 0 arguments, 2 provided
         map<details::http_endpoint, http_resource*>::value_type(idx, hrm)
                                                                         ^
Makefile:530: recipe for target 'libhttpserver_la-webserver.lo' failed
make[2]: *** [libhttpserver_la-webserver.lo] Error 1
make[2]: Leaving directory '/home/iram14/Downloads/httpserver/libhttpserver/build/src'
Makefile:592: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/iram14/Downloads/httpserver/libhttpserver/build'
Makefile:479: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by etr** [comment]
Hey,
thanks for notifying. Would you be able to tell me the values of the points below?

1) version of ubuntu (and kernel version)
2) the compiler you are using
3) the version of libmicrohttpd

**Comment by Rajkumar181** [comment]
1. version of ubuntu (and kernel version)
=>  ubuntu 18.04
2. the compiler you are using
=> Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.3.0-27ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04) 

3. the version of libmicrohttpd
=> libmicrohttpd-0.9.52

**Comment by etr** [comment]
Hey,
I've now been working on a new vanilla AWS instance with an installation of ubuntu 18.04. I am not being able to reproduce this problem and the library builds correctly.
The output of my config.log matches the one you have pasted. Are you still seeing the error with the latest versions of the library (latest release or head)?

Also, would you be able to retry with libmicrohttpd-0.9.56 ? (It should be uncorrelated but it would match with the version on which automated tests are being currently executed)

**Comment by etr** [comment]
Closing as we are not being able to reproduce the problem on head (despite using the same operating system version and kernel version, compiler version and dependency versions)

**Comment by nmarandi** [comment]
I have this issue too. @etr

**Comment by etr** [comment]
Hi,
I will need you to help me reproduce.
Are you running with the latest version on head (from yesterday)? If not, can you please indicate your tag or commit number?
On the latest there is no map construction at the line you reference.
I've also just built with g++-9 (albeit on Ubuntu) and everything goes fine.

**Comment by nmarandi** [comment]
Hi, and thanks. The master branch was compiled successfully but this error happened when I want compile the v0.11.1 Tag.

**Comment by etr** [comment]
Hi,
version 0.11.1 is quite old (2016). Is there something blocking you from using more recent versions of the library? See: https://github.com/etr/libhttpserver/releases

0.17.5 is the most recent one and recommended. Given a recent set of fixes, I will likely push another minor release of 0.17 in the next few days.
