### ISSUE TITLE
[BUG] Segmentation fault

### ISSUE THREAD

**Issue by kyku** [etr/libhttpserver#147]
### Prerequisites

* [X] Put an X between the brackets on this line if you have checked that your issue isn't already filed: https://github.com/search?l=&q=repo%3Aetr%2Flibhttpserver&type=Issues

### Description

Segmentation fault

### Steps to Reproduce

1. Start daemon on a port which is already open

**Expected behavior:** Exception is correctly reported.

**Actual behavior:** Segmentation faults or string truncation depending on port value.

**Reproduces how often:** 100%

### Versions

* OS version Linux XXX 5.0.9-arch1-1-ARCH #1 SMP PREEMPT Sat Apr 20 15:00:46 UTC 2019 x86_64 GNU/Linux
* libhttpserver version master 
* libmicrohttpd version does not matter

### Additional Information
Caused by webserver.cpp:328 
throw std::invalid_argument("Unable to connect daemon to port: " + this->port);
needless to say, this increments to pointer rather than appends to string.

**Comment by kyku** [comment]
Possible fix:
`throw std::invalid_argument("Unable to connect daemon to port: " + std::to_string(this->port));`

**Comment by etr** [comment]
Fix is on head. Thanks for notifying.
