### ISSUE TITLE
Method PATCH and DELETE

### ISSUE THREAD

**Issue by kapacbspb** [etr/libhttpserver#150]
It is impossible to implement standard HTTP / 1.1 PATCH in the standard library version. Maybe I'm confusing something and you can use PUT, but this is not quite RESTful.

When using the DELETE method with any body, the client does not receive a response from the server, as time passes, the answer comes: `Error: Server returned nothing (no headers, no data)`

```
const std::shared_ptr<httpserver::http_response>
source_resource::render_DELETE(const httpserver::http_request &req)
{
  httpserver::string_response* response = new httpserver::string_response("{\"result\":\"ok\"}", 200);
  response->with_header("Content-Type","application/json");
  return std::shared_ptr<httpserver::http_response>(response);                         
}
```

**Comment by etr** [comment]
The version on head of master addresses both the issues. Please reopen if you still observe a problem.
