### ISSUE TITLE
redirect does not work

### ISSUE THREAD

**Issue by mangup** [etr/libhttpserver#164]
I've modified example to answer with 302 code:

`return std::shared_ptr<http_response>(new string_response("http://example.com", 302));`

but redirection didn't happen - only text "http://example.com" appeared.

how to do redirection properly?

**Comment by etr** [comment]
Hi,

this is not a bug. Regular HTTP clients will get the destination of a 302 redirection from headers. What you are doing there is setting the body of the response to "http://example.com" that's why you just see that printed.

In the response, set the location header:

    response->with_header("Location", "http://example.com");
