### ISSUE TITLE
[BUG] performance issue ? httperf rate

### ISSUE THREAD

**Issue by mangup** [etr/libhttpserver#169]
I've tested it with httpperf on localhost:
"./httperf --hog --port=8080 --server=127.0.0.1 --uri=/hello --num-calls=100 --num-conns=10000" works well. result is 
"Request rate: 26716.5 req/s, test-duration 37.430 s."

but when I've add rate option:
 "./httperf --hog --rate=27000 --port=8080 --server=127.0.0.1 --uri=/hello --num-calls=100 --num-conns=10000" gives result 
"Request rate: 726.8 req/s test-duration 581.873 s"

What is the problem?

PS another my (golang) httpsever works well on this commands.

**Comment by etr** [comment]
From your commands it is quite normal that the request rate is higher in the first use-case versus the second.
In your second use-case, you are essentially shooting 27k req/s but allowing only 10k connections to be served (which by definition will queue) - also, if you are using the source from the hello_world sample, you are just using a thread-pool of size 5 which will further worsen the queueing of requests.
In general, if you traffic is spiky, you might want to use a different running model for the webserver (generally a thread per connection model wins with a high number of requests in a single spike). Tuning the execution model and the number of threads will improve the performance you get from the library. Ideally, you'll want to calibrate these on the hardware you have at hand.
I am not sure what execution model your golang server uses but it might be closer to an ideal one for the specific task.

**Comment by mangup** [comment]
Hi, Sebastiano. thank you for answer.
I did not quite understand. I use example  url_registration.cpp
command "./httperf --hog --port=8080 --server=127.0.0.1 --uri=/hello --num-calls=100 --num-conns=10000" result is "Request rate: 24890.0 test-duration 40.177 s"
but
command "./httperf --hog --port=8080 --server=127.0.0.1 --uri=/hello --num-calls=100 --num-conns=10000 --ra=10000" result is "Request rate: 2925.8 test-duration 215.744 s"
