### ISSUE TITLE
Newbie Linux start with hello world microhttpd.h

### ISSUE THREAD

**Issue by jophof** [etr/libhttpserver#170]
Hope that you can help me.

I am new to Liunx (most knwledge come from the DOS era :-)) My main machine is OSx but compilation c++ is a nightmare.

I need to get a rest server going including TLS. 

No github project could make it to a hello world example working. Since I am new to build make configure .h it is hard for me. 

When I do ../configure on your project I got stuck here:

configure: WARNING: "gnutls/gnutls.h not found. TLS will be disabled"

checking microhttpd.h usability... no

checking microhttpd.h presence... no

checking for microhttpd.h... no

configure: error: "microhttpd.h not found"

All though I installed libmicrohttpd-0.9.68 as well I did build and configure on this project.

I copied  microhttpd.h file in many directories but where to put this file??

My compiler is this one:

g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)

Copyright (C) 2015 Free Software Foundation, Inc.

My kernel version is
3.10.0-1062.el7.x86_64

My plain vanilla compile trial is this:
g++ hellow.cc -o hellow_server -L/usr/include/mysql-lmysqlclient -I/usr/include/mysql -I/media/psf/Home/centOS/libhttpserver-master/src
trhowing a lot of comile errors. I could not find a way to compile it properly.
In most of my project I can make a solutioin after I pass the helloworld initial state.

If you got me going I love to sponsor your project!

**Comment by vankofalcon** [comment]
@jophof I think you should install libmicrohttpd first

**Comment by jophof** [comment]
I installed  libmicrohttpd first also

**Comment by etr** [comment]
Hey,
thanks for using the library. For some reason, the configure is not finding libmicrohttpd. How did you install it (brew or compiled from scratch?)
Would you be able to tell where in your system the microhttpd.h header file is stored? (Possibly using locate or otherwise, if you compiled libmicrohttpd from scratch, you can see it in the config.log)

I think we will have a second problem later (you don't have gnutls installed on your system and you'll need that for sale) but let's get the library to compile first and then worry about that.

**Comment by jophof** [comment]
Thanks for your feedback! I tried to mail you but got a bounce and maybe this is better to share with the community.
Hi brews is for apple I am developing on CentOS (virtualised parallels machine). In the attachment my complete development tree maybe that tells the whole story I try to upload it but 272 Mb is not possible.
So I did ls -lR on my development tree getting this. 
https://docs.google.com/document/d/1wbjRh26acmiPrGHz10LVJSkhnVqUD3NIkSE0DowWXBc/edit?usp=sharing
The only thing I need is the step(s) to be taken to get hello world running.  

For every package I follow the instructions last weekend I tried lots of them no one of them could bring a hello world example running.
Thanks in advance! and have a  fine weekend!!

**Comment by etr** [comment]
The configure from libhttpserver expects libmicrohttpd to be installed in the system and reachable in standard paths. In essence, it searches for the "microhttpd.h" header file within the following paths: "/usr/include/" and "/usr/local/include". Similarly, it searches for the "libmicrohttpd.so" file within the following paths: "/usr/lib" and "/usr/local/lib".

Of course, all of the above assuming you didn't change you prefix within your configure (in which case you just have to re-use the same prefix on both libraries).

Going back to the original question of "did you install libmicrohttpd?", can you confirm the steps you did to compile and install it? The easiest (by far) way to obtain the result you seek is to download the libmicrohttpd code, compile and install it manually.

My recommendation is to discard whatever your current state and restart from scratch (I saw you copied headers a bit all over).

To do so you should follow the instructions in their readme. To make your life easy:

Download the library from this link: https://ftp.gnu.org/gnu/libmicrohttpd/libmicrohttpd-0.9.68.tar.gz

    tar -xvzf libmicrohttpd-0.9.68.tar.gz
    cd libmicrohttpd-0.9.68
    mkdir build
    cd build
    ../configure
    make
    sudo make install

Once you have done so, download libhttpserver and follow the instruction in the README for installation. It should all just work.

If you do this and it still doesn't work, let's set some time and chat on gitter ( https://gitter.im/libhttpserver/community ) it might speed-up your turn-around time.

**Comment by jophof** [comment]
Hi thanks this is enormous goud feedback which I will put in practice! Maybe you can put it somewhere in readme or somewhere else for other newbies.

Thanks!!!!

**Comment by etr** [comment]
The code of the two libraries is largely developed independently, with my library (libhttpserver) depending on libmicrohttpd. Given independence of development, the documentation must be kept independent too - they have a set of options (that I skipped above for brevity); if I were to repeat within my own documentation, it would result in a dangerously redundant readme, with the risk of becoming incorrect whenever they make a change on their side.

Most of the suggestion on top, depends on knowledge of _autotools_ that are also developed independently of this library (and its other dependencies) and equally documented independently - the topic, in this case, is so broad that books and entire websites have been written on the purpose. This again, becomes recursive, the more you dig into dependencies (linux, your specific distro, TCP, HTTP, etc.).

If I might suggest, and if you are just restarting now to develop code in this space, I would recommend reading/documenting yourself about:

- linux and unix (platform where you intend to run): https://amazon.com/dp/1593272200
- TCP/IP: https://amazon.com/dp/B00666M52S
- HTTP Protocol: https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview
- autotools: https://www.gnu.org/software/automake/manual/html_node/Autotools-Introduction.html
- libmicrohttpd: https://www.gnu.org/software/libmicrohttpd/manual/libmicrohttpd.html
- finally libhttpserver own readme

Closing this issue for now - let me know if you need any help.
