### ISSUE TITLE
Little help making 'hello world' work

### ISSUE THREAD

**Issue by vankofalcon** [etr/libhttpserver#171]
I want to run the hello world example.
I've managed to build and install first libmicrohttpd-0.9.68 and then libhttpserver (lastest from master).
My CMakeLists.txt looks like this

cmake_minimum_required(VERSION 3.15)
project(libhttpserver1)

set(CMAKE_CXX_STANDARD 17)

list(APPEND CMAKE_MODULE_PATH "/usr/local/share/cmake/Modules/")

find_package(LibHttpServer REQUIRED)

add_executable(${PROJECT_NAME} main.cpp)

message(STATUS "${LIBHTTPSERVER_INCLUDE_DIRS}, ${LIBHTTPSERVER_LIBRARIES}")

target_include_directories(${PROJECT_NAME} PRIVATE ${LIBHTTPSERVER_INCLUDE_DIRS})
target_link_libraries(${PROJECT_NAME} PRIVATE ${LIBHTTPSERVER_LIBRARIES})

The build is successful and the message output is:
-- /usr/local/include, /usr/local/lib/libhttpserver.so

my main.cpp file:

#include <httpserver.hpp>

using namespace httpserver;

class hello_world_resource : public http_resource {
public:
    const std::shared_ptr<http_response> render(const http_request&) {
        return std::shared_ptr<http_response>(new string_response("Hello, World!"));
    }
};

int main(int argc, char** argv)  {
    webserver ws = create_webserver(8080);
    hello_world_resource hwr;
    ws.register_resource("/hello", &hwr);
    ws.start(true);
    return 0;
}

Everything looks OK until I run the application. I get an error:
`error while loading shared libraries: libmicrohttpd.so.12: cannot open shared object file: No such file or directory
`
That file is located in /usr/local/lib/ but it can't be found as the error states.
What I got in /usr/local/lib is
libhttpserver.la  libhttpserver.so.0       libmicrohttpd.a   libmicrohttpd.so     libmicrohttpd.so.12.55.0  
libhttpserver.a  libhttpserver.so  libhttpserver.so.0.17.5  libmicrohttpd.la  libmicrohttpd.so.12

g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
cmake version 3.15.5

How to make this work? Thx

**Comment by etr** [comment]
Not sure why this was marked as a bug.

I think your system might not have resolved the linked libmicrohttpd. You can see if this is true by running:

   ldd libhttpserver.so.0.17.5

from you /usr/local/lib

I believe that would show you that libmicrohttpd is not resolved/cached.

To solve just run:

    sudo ldconfig

I hope this helps. Let me know.

**Comment by vankofalcon** [comment]
Thx @etr :bowing_man:
