### ISSUE TITLE
Trying to set up https

### ISSUE THREAD

**Issue by Panshangka** [etr/libhttpserver#172]
Hello, I successfully install libhttpserver on Ubuntu19.04 and all the http demos worked out fine.
But when I try to run ./minimal_https under build/examples directory, an error occured:
  terminate called after throwing an instance of 'std::invalid_argument'
      what(): Unable to connect daemon to port : 8080 

which is the same error as : https://github.com/etr/libhttpserver/issues/97
But I generated my key and certificate throungh: 
  $ openssl genrsa -des3 -passout pass:x -out server.pass.key 2048
  $ openssl rsa -passin pass:x -in server.pass.key -out server.key
  $ openssl req -new -key server.key -out server.csr
  $ openssl x509 -req -days 365 -in server.csr -signkey server.key -out server.crt

I don't know where I made a mistake.  What I have configured is:
  install libmicrohttpd (compile from source code)
  install libgnutls(compile from source code)

Please help, thanks.

**Comment by etr** [comment]
Hey,

did you modify the example to match the names of your key and certificate? At the moment it searches for "key.pem" and "cert.pem". You should make it match yours "server.key" and "server.crt".

Also, did you add a challenge password on your certificate?

**Comment by Panshangka** [comment]
Yes, the names are ok and also I added a challenge password

**Comment by etr** [comment]
The challenge password might be the problem.

Can you try to generate both for me as follows and see if it works for you?

    openssl genrsa -out server.key 2048
    openssl req -days 365 -out server.crt -new -x509 -key server.key

**Comment by Panshangka** [comment]
The problem still exist, but I tried this on another computer, what I did:
  install libmicrohttpd (not compile source but apt install libmicrohttpd-dev)
  install libhttpserver
Then a success, really confused

**Comment by etr** [comment]
I was re-reading your first e-mail. Did you compile/install libmicrohttpd **before** compiling/installing libgnutls ?
If so, the configure script of libmicrohttpd would not have found gnutls installed and would have disabled it (you can check the config.log in libmicrohttpd to confirm).
Can you please try re-compiling/installing libmicrohttpd **after** having compiled/installed libgnutls and check if everything works in that case?

If you are using libmicrohttpd-dev from ubuntu, that tries to have all possible options enabled so it would depend on libgnutls-dev to make sure that tls is enabled by default (that it why it worked on your other computer).

**Comment by Panshangka** [comment]
Thanks, I successfully set up https and I think the easiest way is to install sudo apt-get install libmicrohttpd-dev cause build from source may cause some problems probably.
My ubuntu version is 16.04 and libmicrohttpd version is lower than required. So I add the source.list https://www.dotdeb.org/instructions/ then a success.

**Comment by etr** [comment]
Happy to know it worked for you.
