### ISSUE TITLE
Having two servers simultaneously [Question]

### ISSUE THREAD

**Issue by naiteon** [etr/libhttpserver#173]
Hello! First of all thank you for this master piece. I really love your lib dude!
I'd like to know if it is possible to have two instances of webserver running?

I ask you that cause I'd like to have only one executable and two sockets, one with SSL and another without, sharing the same resources.

Is it achievable?

**Comment by etr** [comment]
Hey,

thanks for using the library. Yes, that is achievable. You would just need to create two webserver objects and run them on independent threads. Bear in mind that if your resources share some state (with concurrent reads and writes), you'll have to manage the concurrent access to that state.

Assuming an extension of the __minimal_https__ example, it would look like this:

    int main(int argc, char** argv) {
        webserver ws_ssl = create_webserver(8443)
            .use_ssl()
            .https_mem_key("key.pem")
            .https_mem_cert("cert.pem");
    
        hello_world_resource hwr;
        ws_ssl.register_resource("/hello", &hwr);
        ws_ssl.start(false);

        webserver ws = create_webserver(8080);
        ws.register_resource("/hello", &hwr);
        ws.start(true);
    
        return 0;
    }

Hope this helps.

PS: Thanks also for sharing the use-case. I think the current interface for register_resource is rather poor (gets a pointer in input, whereas it should take a shared_ptr). It is not a problem in practice, but still...
