### ISSUE TITLE
response json object

### ISSUE THREAD

**Issue by Panshangka** [etr/libhttpserver#174]
Hello, my application client only revieve response with json format, but in the document of this repo, It seems that I can't find a solution, the response format:
  string_response: A simple string response.
  file_response: A response getting content from a fail.
  basic_auth_fail_response: A failure in basic authentication.
  digest_auth_fail_response: A failure in digest authentication.
  deferred_response: A response getting content from a callback.

So how can I modify something to satisfy my needs? thanks !

**Comment by etr** [comment]
Hi,
I see you closed this one so I believe you have probably sorted it out.

In any case, Json would just represent the format of your content which is ultimately a string - json itself is a way to represent complex objects as strings.
The other methods (besides string_response) are helper methods to tackle specific situations (e.g. pulling data from a file, having to defer the answer, etc.).
The library itself doesn't take responsibility of the format of your content and doesn't perform serialization/deserialization of complex objects sent through content.
All you need to do to push your json content through a string_response is to convert it plainly in a string if this is somehow modelled through C++ objects. I would expect any json library you are using to be giving you such option given it is the whole purpose of json.

Hope this helps.

**Comment by Panshangka** [comment]
Thanks, I sorted it out!
