### ISSUE TITLE
the question of 'SSL handshark abort'

### ISSUE THREAD

**Issue by wning123456** [etr/libhttpserver#175]
When my front end requests the server, an error is reported,'SSL handshark baort'.The problem came out of the blue. It was fine before.
The SSL certificate is free to apply for on pay treasure, deadline is one year.
These are my questions and I look forward to your reply.

**Comment by naiteon** [comment]
@wning123456  Hey dude, what is the openssl / gnutls version you are linking it against? And does that occur on every single connection? Or intermittently ?
