### ISSUE TITLE
[BUG] Use of deprecated MHD_HTTP_UNORDERED_COLLECTION 

### ISSUE THREAD

**Issue by bcsgh** [etr/libhttpserver#176]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have checked that your issue isn't already filed: https://github.com/search?l=&q=repo%3Aetr%2Flibhttpserver&type=Issues

### Description

Used here:
https://github.com/etr/libhttpserver/blob/c91e2417cce02c259250e81494539f7848ac117a/src/http_utils.cpp#L103

however libmicrohttpd defines it like:

/** @deprecated */
#define MHD_HTTP_UNORDERED_COLLECTION \
  _MHD_DEPR_IN_MACRO ( \
    "Value MHD_HTTP_UNORDERED_COLLECTION is deprecated as it was removed from RFC") \
  425
https://git.gnunet.org/libmicrohttpd.git/tree/src/include/microhttpd.h?h=v0.9.69&id=3a661f8675e4312f5c02339a0dcd44bf0a5fcef5#n498

Note 1: This seems to have been chnaged c2019/07
https://lists.gnu.org/archive/html/gnunet-svn/2019-06/msg00286.html

Note 2: I was able to work around this by building that file with -DMHD_NO_DEPRECATION

### Steps to Reproduce

1. compile with -Werror

**Expected behavior:** [What you expect to happen]

Build without warnings or errors

**Actual behavior:** [What actually happens]

Warning/Error -> "Value MHD_HTTP_UNORDERED_COLLECTION is deprecated as it was removed from RFC"

**Reproduces how often:** 100%

### Versions

See link above for srv versions, OS shouldn't matter. 

If you have problems during build:
* Compiler version: GCC

**Comment by etr** [comment]
Thanks for notifying. It might be about time to update those constants in bulk. I will post a fix in the next few days.

**Comment by LeSpocky** [comment]
FWIW: this definition was deprecated with libmicrohttpd v0.9.63-113-gbadb814e and thus was released with libmicrohttpd v0.9.64 in June 2019. I did not notice this because I was mostly building against libmicrohttpd v0.9.62 from Debian 10 (buster), which is currently the _oldstable_ Debian release.

**Comment by bcsgh** [comment]
Thank!
