### ISSUE TITLE
[BUG] Documentation issues.

### ISSUE THREAD

**Issue by bcsgh** [etr/libhttpserver#178]
* [X] Put an X between the brackets on this line if you have checked that your issue isn't already filed: https://github.com/search?l=&q=repo%3Aetr%2Flibhttpserver&type=Issues

### Description

- The Community/Contributing link in READEME.md links to the code-of-conduct.
- The email that CODE_OF_CONDUCT.md and CONTRIBUTING.md list for reporting issues to is dead. ("DNS type 'mx' lookup of zencoders.org responded with code NXDOMAIN", looks like this expired a few months ago? Or should that be zencoders.com?).

**Comment by etr** [comment]
All links and e-mails referred in this issue have been updated.
