### ISSUE TITLE
Undefined reference to `httpserver::webserver::webserver(httpserver::create_webserver const&)'

### ISSUE THREAD

**Issue by GabrieleHitachi** [etr/libhttpserver#194]
### Description

I try to use this library, i install libhttpserver-0.17.5 and i make a little program (see below).
I include the library and apparently all is correct. When i build the solution i receive this error:
'undefined reference to `httpserver::webserver::webserver(httpserver::create_webserver const&)'
'undefined reference to `httpserver::webserver::~webserver()'

### Steps to Reproduce

#include <httpserver.hpp>
using namespace httpserver;

int main() {
  webserver ws = create_webserver(8080);
}

When i build my project i receive an error:
'undefined reference to `httpserver::webserver::webserver(httpserver::create_webserver const&)'
'undefined reference to `httpserver::webserver::~webserver()'

i try with this other code:

#include <httpserver.hpp>
using namespace httpserver;

int main() {

  const create_webserver& temp = create_webserver(8080);
  webserver ws(temp);
}

When i build my project i receive an error, always during instantiation of webserver object (no error in line const create_webserver& temp = create_webserver(8080))
'undefined reference to `httpserver::webserver::webserver(httpserver::create_webserver const&)'
'undefined reference to `httpserver::webserver::~webserver()'

### Versions

* Ubuntu 20.04 LTS 
* libhttpserver-0.17.5
* libmicrohttpd-dev 0.9.66-1

If you have problems during build:
* g++ 9.3.0
* autotools-dev 20180224.1
* autoconf 2.69-11.1.

**Comment by wkibbler** [comment]
Im also having this problem, did you manage to fix it @GabrieleHitachi ?

**Comment by etr** [comment]
Did you try running "ldconfig" to refresh your cache of shared libs after you've installed libhttpserver?

**Comment by wkibbler** [comment]
Doesn't seem to help

**Comment by Befeepilf** [comment]
Make sure that `ld` is aware of libhttpserver by running `ldconfig -v | grep libhttpserver` and that you include libhttpserver when linking.
In my case, the shared libraries where installed under `/usr/local/lib` and `ld` didn't check that directory. In addition I wasn't telling g++ to also link libhttpserver.
Adding `/usr/local/lib` to `/etc/ld.so.conf`, running `sudo ldconfig` and adding `-lhttpserver` to my g++ linking command resolved this issue.
