### ISSUE TITLE
Access-Control-Allow-Origin for all response headers

### ISSUE THREAD

**Issue by jfdoolster** [etr/libhttpserver#195]
**Is your feature request related to a problem? Please describe.**
Trying to develop a front-end UI for libhttpserver REST API. CORS errors do not allow communication between api and front-end ports. Header can be set using
```
std::shared_ptr<http_response> response = std::shared_ptr<http_response> (new string_response("HELLO"));
response->with_header("Access-Control-Allow-Origin","*");
return response;
```
but need to add this to _all_ responses. **We request a method to globally add this header to all http responses to remove CORS errors.**  

**Describe why the feature or enhancement you are proposing fits the library.**
While this flag can be added to individual requests, avoiding CORS errors requires this to be added at to each response. This method will likely lead to bugs as server grows in complexity. 

**Describe the solution you'd like**
We request a method of adding the the 'Access-Control-Allow-Origin' header to **all** http responses to avoid CORS (Cross-Origin Resource Sharing) errors. 

**Describe alternatives you've considered**
libhttpserver currently requires the use of the with_header() function for each response. With all responses requiring the same header to remove CORS errors, this requirement will likely lead to bugs. 

Thank you!

**Comment by hengzZ** [comment]
How did you remove the CORS errors?  And could you give me some example code? Thank you!
