### ISSUE TITLE
[FEATURE] missing support for dualstack ipv6+ipv4

### ISSUE THREAD

**Issue by vandalon** [etr/libhttpserver#202]
libhttpserver only support either ipv4 OR ipv6.
It would be nice to have support for both at the same time (dualstack).

proposed fix:

webserver.cpp:313;
use MHD_USE_DUAL_STACK instead of MHD_USE_IPv6 or add a new option for dual stack.

(thanks to my colleague for researching this.)

**Comment by etr** [comment]
Interesting. Let me take a look to see if it has other implications within the library with the current implementation (e.g. blocking IPs).

**Comment by etr** [comment]
This feature is now on head. Thanks for requesting it.
