### ISSUE TITLE
[BUG] Build failure with latest from git

### ISSUE THREAD

**Issue by chrisfw** [etr/libhttpserver#211]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have checked that your issue isn't already filed: https://github.com/search?l=&q=repo%3Aetr%2Flibhttpserver&type=Issues

### Description

Build failure occurs with latest git version

### Steps to Reproduce

1.  Run configure and make per standard build instructions

**Expected behavior:** Successful build

**Actual behavior:** Build Failure
```
In file included from ../../src/httpserver/create_webserver.hpp:30:0,
                 from ../../src/httpserver/webserver.hpp:49,
                 from ../../src/webserver.cpp:21:
../../src/httpserver/http_response.hpp:58:9: error: function 'httpserver::http_response::http_response(httpserver::http_response&&)' defaulted on its first declaration with an exception-specification that differs from the implicit declaration 'httpserver::http_response::http_response(httpserver::http_response&&)'
         http_response(http_response&& b) noexcept = default;
         ^
../../src/httpserver/http_response.hpp:61:24: error: function 'httpserver::http_response& httpserver::http_response::operator=(httpserver::http_response&&)' defaulted on its first declaration with an exception-specification that differs from the implicit declaration 'httpserver::http_response& httpserver::http_response::operator=(httpserver::http_response&&)'
         http_response& operator=(http_response&& b) noexcept = default;
                        ^
In file included from ../../src/httpserver/details/modded_request.hpp:28:0,
                 from ../../src/webserver.cpp:54:
../../src/httpserver/http_request.hpp:230:9: error: function 'httpserver::http_request::http_request(httpserver::http_request&&)' defaulted on its first declaration with an exception-specification that differs from the implicit declaration 'httpserver::http_request::http_request(httpserver::http_request&&)'
         http_request(http_request&& b) noexcept = default;
         ^
In file included from ../../src/webserver.cpp:56:0:
../../src/httpserver/http_resource.hpp:214:9: error: function 'httpserver::http_resource::http_resource(httpserver::http_resource&&)' defaulted on its first declaration with an exception-specification that differs from the implicit declaration 'httpserver::http_resource::http_resource(httpserver::http_resource&&)'
         http_resource(http_resource&& b) noexcept = default;
         ^
In file included from ../../src/webserver.cpp:59:0:
../../src/httpserver/string_response.hpp:54:9: error: function 'httpserver::string_response::string_response(httpserver::string_response&&)' defaulted on its first declaration with an exception-specification that differs from the implicit declaration 'httpserver::string_response::string_response(httpserver::string_response&&)'
         string_response(string_response&& other) noexcept = default;
```
**Reproduces how often:** 100pct

### Versions

* OS version (if on linux, the output of "uname -a")
Linux docker100 3.10.0-1062.1.1.el7.x86_64 #1 SMP Fri Sep 13 22:55:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* libhttpserver version (please specify whether compiled or packaged)  
   latest git as of 10/13.  Compiled.
* libmicrohttpd version (please specify whether compiled or packaged)
  libmicrohttpd-0.9.71. Compiled

If you have problems during build:
* Compiler version - gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
* autotools version - 
autoconf-2.69-11.el7.noarch
automake-1.13.4-3.el7.noarch

[config.log](https://github.com/etr/libhttpserver/files/5371932/config.log)
### Additional Information

Any additional information, configuration (especially build configuration flags if you compiled the libraries) or data that might be necessary to reproduce the issue.

If you have problems during build, please attach your config.log and the full scope of your error from make.
[config.log](https://github.com/etr/libhttpserver/files/5371932/config.log)

If you have problems at execution, please:
* attach the stacktrace in case of crash (a coredump would be even better).
* provide a main that reproduces the error.

**Comment by beneschtech** [comment]
CentOS 7's stock compiler can not build libhttpserver, you need
devtoolset to build it (or upgrade to Cent 8)
Perhaps we should put a version check on gcc in configure to make sure
its at least 5.x
On Tue, 2020-10-13 at 07:17 -0700, Chris W wrote:
> 
> Prerequisites
> 
> [X ] Put an X between the brackets on this line if you have checked
> that your issue isn't already filed: 
> https://github.com/search?l=&q=repo%3Aetr%2Flibhttpserver&type=Issues
> 
> Description
> Build failure occurs with latest git version
> 
> Steps to Reproduce
> 
> Run configure and make per standard build instructions
> 
> Expected behavior: Successful build
> 
> Actual behavior: Build Failure
> 
> In file included from
> ../../src/httpserver/create_webserver.hpp:30:0,                 from
> ../../src/httpserver/webserver.hpp:49,                 from
> ../../src/webserver.cpp:21:../../src/httpserver/http_response.hpp:58:
> 9: error: function
> 'httpserver::http_response::http_response(httpserver::http_response&&
> )' defaulted on its first declaration with an exception-specification 
> that differs from the implicit declaration
> 'httpserver::http_response::http_response(httpserver::http_response&&
> )'         http_response(http_response&& b) noexcept =
> default;         ^../../src/httpserver/http_response.hpp:61:24:
> error: function 'httpserver::http_response&
> httpserver::http_response::operator=(httpserver::http_response&&)'
> defaulted on its first declaration with an exception-specification
> that differs from the implicit declaration
> 'httpserver::http_response&
> httpserver::http_response::operator=(httpserver::http_response&&)'   
>       http_response& operator=(http_response&& b) noexcept =
> default;                        ^In file included from
> ../../src/httpserver/details/modded_request.hpp:28:0,                
>  from
> ../../src/webserver.cpp:54:../../src/httpserver/http_request.hpp:230:
> 9: error: function
> 'httpserver::http_request::http_request(httpserver::http_request&&)'
> defaulted on its first declaration with an exception-specification
> that differs from the implicit declaration
> 'httpserver::http_request::http_request(httpserver::http_request&&)' 
>         http_request(http_request&& b) noexcept =
> default;         ^In file included from
> ../../src/webserver.cpp:56:0:../../src/httpserver/http_resource.hpp:2
> 14:9: error: function
> 'httpserver::http_resource::http_resource(httpserver::http_resource&&
> )' defaulted on its first declaration with an exception-specification 
> that differs from the implicit declaration
> 'httpserver::http_resource::http_resource(httpserver::http_resource&&
> )'         http_resource(http_resource&& b) noexcept =
> default;         ^In file included from
> ../../src/webserver.cpp:59:0:../../src/httpserver/string_response.hpp
> :54:9: error: function
> 'httpserver::string_response::string_response(httpserver::string_resp
> onse&&)' defaulted on its first declaration with an exception-
> specification that differs from the implicit declaration
> 'httpserver::string_response::string_response(httpserver::string_resp
> onse&&)'         string_response(string_response&& other) noexcept =
> default;
> Reproduces how often: 100pct
> 
> Versions
> 
> OS version (if on linux, the output of "uname -a")
> 
> Linux docker100 3.10.0-1062.1.1.el7.x86_64 #1 SMP Fri Sep 13 22:55:44
> UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
> libhttpserver version (please specify whether compiled or packaged)
> 
> latest git as of 10/13.  Compiled.
> libmicrohttpd version (please specify whether compiled or packaged)
> 
> libmicrohttpd-0.9.71. Compiled
> 
> If you have problems during build:
> 
> 
> Compiler version - gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
> autotools version -
> 
> autoconf-2.69-11.el7.noarch
> 
> automake-1.13.4-3.el7.noarch
> 
> config.log
> 
> Additional Information
> Any additional information, configuration (especially build
> configuration flags if you compiled the libraries) or data that might
> be necessary to reproduce the issue.
> 
> If you have problems during build, please attach your config.log and
> the full scope of your error from make.
> 
> config.log
> 
> If you have problems at execution, please:
> 
> 
> attach the stacktrace in case of crash (a coredump would be even
> better).
> provide a main that reproduces the error.
> 
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> [
> {
> "@context": "http://schema.org",
> "@type": "EmailMessage",
> "potentialAction": {
> "@type": "ViewAction",
> "target": "https://github.com/etr/libhttpserver/issues/211",
> "url": "https://github.com/etr/libhttpserver/issues/211",
> "name": "View Issue"
> },
> "description": "View this Issue on GitHub",
> "publisher": {
> "@type": "Organization",
> "name": "GitHub",
> "url": "https://github.com"
> }
> }
> ]
-- 
Chris Benesch <chris@beneschtech.com>

**Comment by etr** [comment]
Yep, the minimum version is 5.5.0 (refer to the documentation).

I'll see what I can do to make configure fail spitting out a clearer error (I'd rather do it capability based than version based, to avoid having issues with other compilers). Opened a specific issue on that (https://github.com/etr/libhttpserver/issues/212) and closing this one.

**Comment by chrisfw** [comment]
Thank you for the info.

Regards,
Chris Whelan
