### ISSUE TITLE
Any example on how to process a multi-part post of a file? Does it even support?

### ISSUE THREAD

**Issue by pfiliberti** [etr/libhttpserver#220]
Does the library currently support an upload of a file using multi-part post?

Is there any example?

**Comment by pfiliberti** [comment]
So far it works with a small jpeg being sent up. I retrieve the data as a string and strings CAN hold binary unsigned char data so no I will try larger data sizes I'm sure it will work.

**Comment by etr** [comment]
Hey,

sorry for the late response on this. Yes, the library supports the retrieval of multi-part automatically within the content. Let me know if it causes you any problems, but generally, it should be transparent.
