### ISSUE TITLE
libhttpserver + libtorch = error of bad_alloc

### ISSUE THREAD

**Issue by xuexl** [etr/libhttpserver#224]
I use libhttpserver for http-service  in last project, it works well. 
But when libhttpserver is used with libtorch in one project, one error is throwed, the message is "terminate called after throwing an instance of 'std::bad_alloc'" ,i check the memory of my computer, when about 7GB is used, then the process is stoped.
Libtorch is a c++ version of Pytorch, a frame of CNN. My procedure of libtorch works well in other projects.
I use Qt and cmake for developing all the time, and my system is Debian10.
So, Help me please, Thank you.

**Comment by etr** [comment]
Hi, thanks for using libhttpserver.

Would you be able to share some code and/or a dump of your error?

**Comment by xuexl** [comment]
First, thanks for your reply.

/** CMakeLists.txt ***/

cmake_minimum_required(VERSION 3.14)

project(HttpServerProxy LANGUAGES CXX)

set(CMAKE_INCLUDE_CURRENT_DIR ON)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(Torch_DIR ~/software/libtorch/share/cmake/Torch)
find_package(Torch REQUIRED)

include_directories(
    ./libhttpserver/include)
link_directories(
    ./libhttpserver/lib)
add_executable(HttpServerProxy
  main.cpp
)
target_link_libraries(HttpServerProxy httpserver.so)
target_link_libraries(HttpServerProxy ${TORCH_LIBRARIES})

/** main.cpp ***/

#include <httpserver.hpp>
#include <torch/script.h>

int main()
{

auto module = torch::jit::load("./yolov5s.torchscript.pt");

}

/****************************************************************/
Try debug more then once, i find it can run sometimes.
And the file 'yolov5s.torchscript.pt' is a module of YOLOv5, exported by python.
this file is working well in other project. the size of this file is about 350MB.

The message of error is :
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

**Comment by etr** [comment]
Hey, thanks for sending this over. From your code, while I see that you are including the header for the library, I don't see you actually using it in any way (you don't seem to be initializing any webserver in your main).

To be fair, as the main is, I am not sure how the library can affect your code in any way. Can you please try without libhttpserver and verify if it works?

Essentially changing your Cmake file and main as below:

/** CMakeLists.txt ***/

cmake_minimum_required(VERSION 3.14)

project(HttpServerProxy LANGUAGES CXX)

set(CMAKE_INCLUDE_CURRENT_DIR ON)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(Torch_DIR ~/software/libtorch/share/cmake/Torch)
find_package(Torch REQUIRED)

add_executable(HttpServerProxy
main.cpp
)
target_link_libraries(HttpServerProxy ${TORCH_LIBRARIES})


/** main.cpp ***/

#include <torch/script.h>

int main()
{

auto module = torch::jit::load("./yolov5s.torchscript.pt");

}

**Comment by xuexl** [comment]
If i comment one line code "target_link_libraries(HttpServerProxy httpserver.so)" in the CMakeLists.txt , it works well. 
then when i open this line code, the error happens. It is so strange.

**Comment by xuexl** [comment]
Or,if i comment the code about "Torch", it works well. 
//set(Torch_DIR ~/software/libtorch/share/cmake/Torch)
//find_package(Torch REQUIRED)
//target_link_libraries(HttpServerProxy ${TORCH_LIBRARIES})
... like this, and the code in main.cpp .  

Retain the code of libhttpserver,  the procedure works well.

**Comment by xuexl** [comment]
Libhttpserver is a good tool for me, I use it in my last project.
you can create one demo, and try it.

**Comment by xuexl** [comment]
I find that if i write code like this 
"
target_link_libraries(HttpServerProxy httpserver.so)
target_link_libraries(HttpServerProxy ${TORCH_LIBRARIES})
" 
in the CMakeLists.txt , the error is throwed, the message is "terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc" .

Then, I swap the order of these two line codes. like this.
"
target_link_libraries(HttpServerProxy ${TORCH_LIBRARIES})
target_link_libraries(HttpServerProxy httpserver.so)
" 

It works.  But why ?  I do not know the reason. 

And, I put the codes of libtorch in a *.so file, a shared library in linux. It throw the error again. I am debuging the procedure.

@etr  Do you know the reason ?

**Comment by etr** [comment]
I don't think that the swap does much. As you say above, you don't have consistent failures, so you are likely experiencing spurious errors.

What I believe is happening is that whatever your main is doing is using too much heap, and hence you receive a bad_alloc (which happens when you try to allocate memory but fail). That it happens when you grow your memory to 7GB suggests it might be because of memory exhaustion.
Kind of far-fetched, but the reason you see it more often when both libs are loaded might be because the additional dynamic libraries are using slightly more memory by virtue of being included.

**Comment by xuexl** [comment]
All the errors throwed were solved, the reason was the order of "target_link_libraries".
If somebody encounter the same question with me, try to change the order of "target_link_libraries".
