### ISSUE TITLE
configure arpa/inet.h not found Error 

### ISSUE THREAD

**Issue by KlimeHertz** [etr/libhttpserver#228]
Hi , First thank you for this amazing library. Am triying to compile the lib under Windows MYSYS2 but when i ./configure i get this error configure: error: "arpa/inet.h not found" any idea ?

**Comment by etr** [comment]
Interesting - the configure should not be looking for inet.h on windows (see: https://github.com/etr/libhttpserver/blob/master/configure.ac#L68), so, for some reason, it is not understanding the correct compiler you are running under. Are you using mingw?

You might want to locally modify the configure.ac file to print the host variable used in the line linked. That would give a better idea of what is going on.

**Comment by KlimeHertz** [comment]
Resolved, thanks a lot for your response. Apparently it couldn't read the host variable i replaced the default case with the windows case and it worked. Thank you again and good continuation.

**Comment by etr** [comment]
Happy it worked for you. I am still kind of puzzled on why it wouldn't read the host variable (I'd rather not have others on windows having to modify the file). Was it having any value on the "host" variable or was it coming empty?

**Comment by KlimeHertz** [comment]
In my case the host was empty, i'll try to compile it on an other pc to see if i was doing something wrong or it's reproducible.
