### ISSUE TITLE
[BUG] boostrap option --build

### ISSUE THREAD

**Issue by LeSpocky** [etr/libhttpserver#253]
### Prerequisites

* [x] Put an X between the brackets on this line if you have checked that your issue isn't already filed: https://github.com/search?l=&q=repo%3Aetr%2Flibhttpserver&type=Issues

### Description

Calling the *bootstrap* script with parameter `-build` or `--build` leads to the following error:

    configure: error: "you must configure in a separate build directory"

### Steps to Reproduce

1. Clone the source
2. Call `./bootstrap --build`
3. Watch *configure* fail

**Expected behavior:** libhttpserver is built.

**Actual behavior:** libhttpserver is not built.

**Reproduces how often:** Always.

### Versions

* OS version: Debian GNU/Linux 10 (buster) on amd64
* libhttpserver version: recent master (0.18.2-30-gd79b092)
* libmicrohttpd version: 0.9.62-1 (from Debian)

If you have problems during build:
* Compiler version: GCC 8.3.0 (from Debian)
* autotools version:
  * automake 1.16.1 (from Debian)
  * libtool 2.4.6 (from Debian)
  * autoconf 2.69 (from Debian)

### Additional Information

The problem is the *bootstrap* script does neither create nor change the directory. The script including those options was added with ac2d9697, the same dir build check was added with 264f2f71, both even before the first release v0.1.1. Although that check was made optional with eaa55378 (v0.7.1) the bootstrap script does not make use of that option.

Suggestion: let the script change dir or remove that option, it does not seem to be used for years now, otherwise someone would have reported or fixed it already?

**Comment by etr** [comment]
I think the real situation is that most people (me included) don't run bootstrap that way, so we didn't spot it. Running bootstrap, creating the directory, and then configure, did make us miss the error. Needs fixing nonetheless, but the separate directory is very much what we want to do. The boostrap script should just create it and move.
