### ISSUE TITLE
Unable to get the link status between client and server

### ISSUE THREAD

**Issue by XinHengW** [etr/libhttpserver#271]
[Description of the issue]

### Steps to Reproduce

1. The client initiates a get request to download a file
2. The server returns the contents of the file requested by the client
3.Webserver needs to know when the request is completed

**Expected behavior:** 

The server can know whether the request has been completed through an interface
**Actual behavior:**
Except for the request from the client and the unexpected error prompt, the server cannot receive any other information

### Versions

* linux

**Comment by etr** [comment]
Marking this as a feature request as it doesn't seem to be a bug but more a new behavior that we are asking the library to support.

The way this is described it doesn's sound like a low-level behavior of the protocol/engine that we are trying to build, rather it is something specific to an application (in general, the job of the server is done when the connection has completed its cycle).

Clients can already implement this through higher-level APIs (can create an API for the client to send confirmation that a download was completed).

**Comment by XinHengW** [comment]
Yes, this should be a new requirement. The program may need to know whether a session has ended or whether the client has disconnected
