### ISSUE TITLE
Use of C++11 concurrency library instead of pthreads.

### ISSUE THREAD

**Issue by m-renaud** [etr/libhttpserver#45]
To allow for more portable code, would it be feasible to replace the use of pthreads with the new C++11 concurrency library? It could be enabled when configured to build with `cpp0x` support (which at this point should be renamed to `cpp11`). What are your thoughts?

**Comment by LeSpocky** [comment]
Meanwhile C++11 is required and C++14 is recommended for libhttpserver. Can you reconsider this issue? (Just stumbled over a `pthread_mutex_init()` and was surprised because there's platform independent thread and mutex support from C++11 onwards.)

**Comment by etr** [comment]
This issue was raised at a time when the library wasn't even C++11 compatible (outside for custom build flags). I think it does make sense at this point to move to a C++ native implementation.
