### ISSUE TITLE
pkg-config config error

### ISSUE THREAD

**Issue by hedayat** [etr/libhttpserver#57]
In libhttpserver.pc.in there is this line:
Libs: -L${libdir} -lmicrohttpd

Which should be
Libs: -L${libdir} -lhttpserver
instead.

**Comment by bzaborow** [comment]
I think microhttpd as a dependency should be included as well. So:
Libs: -L${libdir} -lmicrohttpd -lhttpserver

**Comment by hedayat** [comment]
I don't think so. According to pkg-config man page, libmicrohttpd should be added to "Requires" (or maybe Requires.private).

**Comment by etr** [comment]
No relevant anymore as the lib doesn't use pkg-config

**Comment by smonkewitz** [comment]
I think this might still be relevant...

In my case, I am implementing an HTTP service using this library. My code uses the [meson](https://mesonbuild.com/) build system, which as far as I can tell, figures out how to link against libhttpserver by reading the libhttpserver.pc pkg-config file installed by homebrew.

If I:

1. Install libhttpserver, meson, and ninja (I'm on OSX 10.14 Mojave):
```brew install libhttpserver meson ninja```

2. Create a file called `bug.cxx` with the following contents:
```c++
#include "httpserver.hpp"

int main() {
    httpserver::webserver server = httpserver::create_webserver();
    return 0;
}
```
and a file named `meson.build` containing:
```
project('bug', 'cpp', default_options : ['cpp_std=c++11'])
dep_libhttpserver = dependency('libhttpserver')
executable('bug', 'bug.cxx', dependencies : dep_libhttpserver)
```
in an empty directory, and then

3.  attempt to build by running:
```
meson build
ninja -C build
```

I get:
```
ninja: Entering directory `build'
[2/2] Linking target bug.
FAILED: bug 
c++  -o bug 'bug@exe/bug.cxx.o' -Wl,-dead_strip_dylibs /usr/local/Cellar/libmicrohttpd/0.9.62_1/lib/libmicrohttpd.dylib -Wl,-headerpad_max_install_names -Wl,-rpath,/usr/local/Cellar/libmicrohttpd/0.9.62_1/lib  
Undefined symbols for architecture x86_64:
  "httpserver::webserver::webserver(httpserver::create_webserver const&)", referenced from:
      _main in bug.cxx.o
  "httpserver::webserver::~webserver()", referenced from:
      _main in bug.cxx.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

Changing the `Lib:` line in libhttpserver.pc as suggested by @hedayat gives me a working build.

**Comment by etr** [comment]
Taking a look

**Comment by etr** [comment]
Fix is on head

**Comment by smonkewitz** [comment]
Thanks!
