### ISSUE TITLE
make with no-use warning

### ISSUE THREAD

**Issue by Smith-WangBing** [etr/libhttpserver#62]
Hi @etr 
Thanks for your work! I have a question.
In class http_request define, this code "
        void set_digested_user(const std::string& user)
        {
            this->digested_user = digested_user;
        }
" should be "
        void set_digested_user(const std::string& digested_user)
        {
            this->digested_user = digested_user;
        }
" ?
Thanks.

**Comment by etr** [comment]
Yes. I definitely should have been - changed the code to avoid this error. Thanks for signaling!
