### ISSUE TITLE
How to build documentation?

### ISSUE THREAD

**Issue by RipcordSoftware** [etr/libhttpserver#63]
I can build the libraries for 0.7.1 and 0.8.0 but I don't see doxygen building the documentation from the source.

It looks like I have to execute `make doxygen-doc` in the build directory as a seperate step - I only know this because I saw it in the `Makefile`, it isn't in the README.md.

Is this the correct way to build the docs or have I just missed something?

**Comment by etr** [comment]
No, it is definitely the right way of producing the doc - I just added a note in the README about it.
