### ISSUE TITLE
A registered root is never invoked

### ISSUE THREAD

**Issue by craigminihan** [etr/libhttpserver#65]
Consider the following:

```c++
  ws.register_resource("/xyz", &xyz_r, false);
  ws.register_resource("/", &root_r, false);
```

Sending a request for /xyz works fine. Sending a request for / always fails with a 404. Setting `family` to `true` then sends unwanted requests like `/abc` to `root_r` which isn't right either.

The problem is due to path handling in `webserver::finalize_answer`, specifically the lines:
```c++
  const char* st_url = mr->standardized_url->c_str();
               
  fe = registered_resources_str.find(st_url);
  if(fe == registered_resources_str.end())
```

Sending a `curl http://localhost:8080/` yields `mr->standardized_url` == "" and not "/" as you might expect. `registered_resources_str` contains "/xyz" and "/" so the `find` always misses resulting in the 404. Ideally `st_url` should be set to "/" when the length of standardized_url is zero.

**Comment by etr** [comment]
Solved by related pull request
