### ISSUE TITLE
Cannot create shared version of Libhttpserver for MinGW using MSYS

### ISSUE THREAD

**Issue by eaguilerai** [etr/libhttpserver#74]
I successfully configure libhttpserver on MSYS, using this command:

../configure --prefix=/mingw --build=x86_64-w64-mingw32 --libdir=/mingw/lib64

where /mingw is a mount point to the root directory of MinGW-w64.

Howerver, when I run make, I get the following warnings that do not allow to build the shared versión of libhttpserver:

**\* Warning: linker path does not have real file for library -lregex.
**\* I have the capability to make that library automatically link in when
**\* you link to this library.  But I can only do this if you have a
**\* shared version of the library, which you do not appear to have
**\* because I did check the linker path looking for a file starting
**\* with libregex and none of the candidates passed a file format test
**\* using a file magic. Last file checked: C:/mingw/msys/1.0/opt/windows_64/lib64/libregex.a

**\* Warning: linker path does not have real file for library -lgpg-error.
**\* I have the capability to make that library automatically link in when
**\* you link to this library.  But I can only do this if you have a
**\* shared version of the library, which you do not appear to have
**\* because I did check the linker path looking for a file starting
**\* with libgpg-error and none of the candidates passed a file format test
**\* using a file magic. Last file checked: C:/mingw/msys/1.0/opt/windows_64/lib64/libgpg-error.dll.a

**\* Warning: linker path does not have real file for library -lws2_32.
**\* I have the capability to make that library automatically link in when
**\* you link to this library.  But I can only do this if you have a
**\* shared version of the library, which you do not appear to have
**\* because I did check the linker path looking for a file starting
**\* with libws2_32 and none of the candidates passed a file format test
**\* using a file magic. Last file checked: c:/mingw/msys/1.0/opt/windows_64/mingw/lib/libws2_32.a
**\* The inter-library dependencies that have been dropped here will be
**\* automatically added whenever a program is linked with this library
**\* or is declared to -dlopen it.

**\* Since this library must not contain undefined symbols,
**\* because either the platform does not support them or
**\* it was explicitly requested with -no-undefined,
**\* libtool will only create a static version of it.

I am not sure, but I think -lregex should be -lgnurx instead, which I have it installed in /mingw/bin. As for gpg-error, I also have the shared versión installed in /mingw/bin. And as for ws2_32, I couldn't find any shared versión installed.

**Comment by deanmsands3** [comment]
Funny enough, I was going to submit a pull-request for this exact issue. Except I have another issue to file first and was running through the list make sure it wasn't a duplicate.

**Comment by etr** [comment]
This is definitely something where the help of someone with mingw/MSYS experience would help a lot. Happy to receive pull-requests in this context especially if those set the base for the library to build more easily (or at all) on windows and can be formalized within travis.
Having lost the main contributors for windows development (and given I am myself far far away from those systems), the library would benefit from help.

**Comment by etr** [comment]
This is now effectively building on travis and executing tests there. Closing.
