### ISSUE TITLE
stop webserver failed.

### ISSUE THREAD

**Issue by Smith-WangBing** [etr/libhttpserver#75]
Hi, When i stop webserver, there is a error:"Fatal error in GNU libmicrohttpd daemon.c:4302: close failed".
I think the problem is "webserver::start" with default "start_method=INTERNAL_SELECT" and with five "max_threads", it will create five "daemon" objects, but the "daemon" objects has the same socket fd. When delete the five daemon items,The function "MHD_stop_daemon" will be call five times, so the socket fd will be repeated closed. It looks like:
^C1======[1318352672]fd(13) shutdown ret(0):Success
3======[1318352672]fd(13) close ret(0):Success
1======[1318352672]fd(13) shutdown ret(-1):Bad file descriptor
3======[1318352672]fd(13) close ret(-1):Bad file descriptor

**Comment by etr** [comment]
This should be easily fixable. The interesting thing is that I didn't see it happening in the past and it is appearing now without major changes in that area of the library.
Could you please share with me which version of libmicrohttpd are you using?

**Comment by Smith-WangBing** [comment]
Thanks for replay.
My libmicrohttpd version is 0.9.39 and 0.9.40. Both of them stop failed.

**Comment by amleivar** [comment]
Hello, still happening with libmicrohttpd version 0.9.42

**Comment by jorisguisson** [comment]
Also ran into this problem. 

It seems to me that the standard INTERNAL_SELECT start method, can only work if you create a socket per MHD_start_daemon call (or maybe use dup to duplicate the socket file descriptor).

I have tried the other start methods, but they didn't work at startup time because the MHD_USE_SELECT_INTERNALLY flag was not passed to MHD_start_daemon. So I modified the start_method_t enum a bit:

   enum start_method_T
    {
        INTERNAL_SELECT = MHD_NO_FLAG,
        THREADS = MHD_USE_THREAD_PER_CONNECTION | MHD_USE_SELECT_INTERNALLY,
        POLL = MHD_USE_SELECT_INTERNALLY | MHD_USE_POLL,
        EPOLL = MHD_USE_SELECT_INTERNALLY | MHD_USE_EPOLL_LINUX_ONLY,
    }

I also added EPOLL.

**Comment by jorisguisson** [comment]
Btw, I'm using libmicrohttpd version 0.9.43

**Comment by etr** [comment]
Both the errors reported in this issue have been fixed.

The server is now stoppable having changed the stop method to use the newly produced quiesce method from libmicrohttpd. The enum has been fixed and simplified to match real use cases more closely.
