### ISSUE TITLE
Cannot override default libmicrohttpd location when cross-compiling for ARM

### ISSUE THREAD

**Issue by masonwinsauer** [etr/libhttpserver#78]
I've been using libhttpserver for some time on Ubuntu 14.04, and now need to cross-compile for ARM. I successfully cross-compiled libmicrohttpd (version 0.9.42) with no issues and then installed it to a custom location on the host system to later reference with libhttpserver. However, I cannot seem to override the default /usr/local/lib search path that libhttpserver uses. Even going into the configure script and hard-coding paths to the cross-compiled versions doesn't work. I'll always get:

checking pkg-config is at least version 0.9.0... yes
checking for LIBMICROHTTPD... no
configure: error: "libmicrohttpd not present or too old - install libmicrohttpd >= 0.9.37"

Many thanks for any advice you can provide.

**Comment by etr** [comment]
libhttpserver uses pkg-config in order to find out where libmicrohttpd is installed.

pkg-config searches for *.pc files in a set of specific folders (usually /usr/lib/pkgconfig, /usr/share/pkgconfig, /usr/local/lib/pkgconfig and /usr/local/share/pkgconfig). If you installed your library in  a custom path, pkg-config is not able to find the *.pc file.

You can provide the location of your *.pc files to pkg-config exporting the PKG_CONFIG_PATH environment variable. This is expressed as a set of paths separated by colon (or semicolon on windows).

I suggest you to find where the file "libmicrohttpd.pc" is in your system and set PKG_CONFIG_PATH variable with the path you find.

**Comment by masonwinsauer** [comment]
Thank you very much for the help. I don't usually work with pkg-config, so that information was very useful.

However, I am now running into an issue where though the configuration recognizes that we're cross-compiling, it sees the CC'd libmicrohttpd.so [`file` correctly gives 'ELF 32-bit LSB  shared object, ARM, dynamically linked, not stripped'] as being in the wrong format.

Is there any other place that I need to specify that the library being brought in is in a non-host format?

**Comment by etr** [comment]
You need to properly set the PKG_CONFIG_SYSROOT_DIR, PKG_CONFIG_DIR and PKG_CONFIG_LIBDIR variables - as you can read from here: https://autotools.io/pkgconfig/cross-compiling.html?utm_source=www.flameeyes.eu&utm_medium=url&utm_campaign=vanitydomainssite

> The wrapper script should not only set the PKG_CONFIG_SYSROOT_DIR variable: when cross-compiling you want to ignore the packages installed in the system, and instead rely only on those installed in the cross-compiled environment. This is achieved by resetting PKG_CONFIG_DIR (which lists additional search paths), and at the same time setting PKG_CONFIG_LIBDIR to override the default base search paths.

**Comment by masonwinsauer** [comment]
My apologies for having this go on for so long, but I had set those after your first comment. However, it doesn't seem to have solved the problem. 

My configuration/build script resembles the following:

`#!/usr/bin/env bash
export PATH=$PATH:/path/to/cross-compilers/

export SYSROOT=/path/to/usr/arm-buildroot-linux-gnueabihf/sysroot/
export PKG_CONFIG_DIR=/path/to/vendor/installed/libmicrohttpd/lib/pkgconfig/
export PKG_CONFIG_SYSROOT_DIR=${SYSROOT}
export PKG_CONFIG_LIBDIR=${SYSROOT}/usr/lib/pkgconfig/
export PKG_CONFIG_PATH=/path/to/vendor/installed/libmicrohttpd/lib/pkgconfig/

export ARCH=arm 
export CROSS_COMPILE=arm-linux-gnueabihf 
../configure --host=arm-linux-gnueabihf --prefix=/path/to/vendor/installed/libhttpserver/

make`

However, libtool is, in some instances, still pointing to x86_64 versions of g++. When manually editing libtool, I get farther in the build process, haven't been able to build fully yet.

**Comment by etr** [comment]
I've modified the configure.ac to avoid the usage of pkg-config. This removes a dependency and a long term pain point for a lot of people trying to compile libhttpserver.

Let me know if this helps in your case.

**Comment by dhruvpajee** [comment]
hi @masonwinsauer i see that you have successfully cross compiled libmicrohttpd for arm. can you please give me some pointers or link to how i can do that? I am trying to build this for pi3. 

thanks in advance!

**Comment by etr** [comment]
Closing this, given we don't use pkg-config anymore
