### ISSUE TITLE
Crashing on calling a virtual method

### ISSUE THREAD

**Issue by shaaaman** [etr/libhttpserver#79]
Hello!
My app throws Seg.Fault when I call my own virtual method of class inherited from httpserver::http_resource<MyClass> inside of callbacks (e.g. render(...), render_GET(...)) or some other class which I use inside of it.

Also, I tried to test  this issue using hello_world example.
Changed
```cpp
void set_some_data(const std::string &s) {data = s;}
```
to
```cpp
virtual void set_some_data(const std::string &s) {data = s;}
```
and when I tried to send GET request it crashed.

**Comment by etr** [comment]
Latest version addresses this problem. It should work as expected now. Let me know if you have any other related problem
