### ISSUE TITLE
using namespace http shows up in headers

### ISSUE THREAD

**Issue by guysherman** [etr/libhttpserver#80]
I have spotted this at the following places:
* http_response.hpp: 55
* http_request.hpp: 47
* http_response_builder.hpp: 48

This forces any file that includes these headers (ie any file that uses your library) to use namespace http. This is widely considered bad practice as it could change the meaning of code in files that include your headers. I was going to use your library but I can't until this is resolved.

**Comment by etr** [comment]
fixed
