### ISSUE TITLE
How do you make it serve pages?

### ISSUE THREAD

**Issue by Wiff3r** [etr/libhttpserver#88]
I got the "Hello World" to compile, and if I go to ".../hello" in the browser, I get "Hello World", but every other address gives me just "Not Found".

I'm confused on how to get it to serve pages other than from /hello. What I need is for it to serve all other pages automatically and only call my code when "/hello" is included.

The other libraries I've used had a "base path" variable where I could tell it where the files were. I do not see anything like that here.

**Comment by etr** [comment]
Hi,
the library does not provide a webserver but just a way to implement them. I think you are trying to implement a file server that should be relatively simple with the api of the library itself.

I'll add an issue to produce an example for this.
