### ISSUE TITLE
Not possible to bind at loopback adresss

### ISSUE THREAD

**Issue by batela** [etr/libhttpserver#90]
Hi all,
I'm trying to restrict the access to the httpserver to local applications. I'm using the constructor as:
 struct sockaddr_in serv_addr;
  /\* Initialize socket structure */
  bzero((char *) &serv_addr, sizeof(serv_addr));

  serv_addr.sin_family = AF_INET;
  serv_addr.sin_addr.s_addr =inet_addr("127.0.0.1");
  serv_addr.sin_port = htons(9899);
create_webserver cw = create_webserver(9899).max_threads(5).bind_address((struct sockaddr *) &serv_addr);

But the application is bind to *:9899,

Is there any restriction for the localhost bind in the libhttpserver? 
Regards

**Comment by etr** [comment]
Taking a look

**Comment by torkve** [comment]
Just got the same problem with version 0.9.1.

**Comment by etr** [comment]
Fixed as part of: https://github.com/etr/libhttpserver/issues/106
