### ISSUE TITLE
Create web server support HTTPS

### ISSUE THREAD

**Issue by tuannv562** [etr/libhttpserver#97]
I compile your example with command: g++ service.cpp -o service -lhttpserver
I start web server with command: ./service -s
Web server start successfully and support HTTPS. I terminated web server by Ctrl-C. Web server stopped.
But I want start web server again with command ./service -s
I received message: **"Unable to connect daemon to port: 8080
terminate called after throwing an instance of 'httpserver::webserver_exception'
  what():  httpserver runtime error"**
Why I can't start web server support HTTPS again?

**Comment by etr** [comment]
Hi,
have you checked if the port is bound by the old process?

**Comment by tuannv562** [comment]
Sorry, This is my mistake. I don't create public key and private key following your guide.

**Comment by etr** [comment]
Ok. Thanks :).
